// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twitos/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the twitos module's genesis state.
type GenesisState struct {
	Params             Params           `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	DbHead             *DbHead          `protobuf:"bytes,2,opt,name=dbHead,proto3" json:"dbHead,omitempty"`
	UserList           []User           `protobuf:"bytes,3,rep,name=userList,proto3" json:"userList"`
	WalletToUserIdList []WalletToUserId `protobuf:"bytes,4,rep,name=walletToUserIdList,proto3" json:"walletToUserIdList"`
	TweetList          []Tweet          `protobuf:"bytes,5,rep,name=tweetList,proto3" json:"tweetList"`
	TweetCount         uint64           `protobuf:"varint,6,opt,name=tweetCount,proto3" json:"tweetCount,omitempty"`
	TweetLikeList      []TweetLike      `protobuf:"bytes,7,rep,name=tweetLikeList,proto3" json:"tweetLikeList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fba4234ae4975edd, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetDbHead() *DbHead {
	if m != nil {
		return m.DbHead
	}
	return nil
}

func (m *GenesisState) GetUserList() []User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *GenesisState) GetWalletToUserIdList() []WalletToUserId {
	if m != nil {
		return m.WalletToUserIdList
	}
	return nil
}

func (m *GenesisState) GetTweetList() []Tweet {
	if m != nil {
		return m.TweetList
	}
	return nil
}

func (m *GenesisState) GetTweetCount() uint64 {
	if m != nil {
		return m.TweetCount
	}
	return 0
}

func (m *GenesisState) GetTweetLikeList() []TweetLike {
	if m != nil {
		return m.TweetLikeList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "hkirat.twitos.twitos.GenesisState")
}

func init() { proto.RegisterFile("twitos/genesis.proto", fileDescriptor_fba4234ae4975edd) }

var fileDescriptor_fba4234ae4975edd = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4b, 0xeb, 0x40,
	0x14, 0xc5, 0x93, 0xd7, 0xbe, 0xbc, 0xe7, 0x54, 0x17, 0x8e, 0x05, 0x43, 0x94, 0x69, 0x11, 0xc1,
	0xae, 0x12, 0xa8, 0xae, 0x44, 0x10, 0xab, 0xa0, 0xa2, 0x0b, 0xa9, 0x15, 0xa1, 0x9b, 0x90, 0x98,
	0x21, 0x0d, 0xfd, 0x33, 0x25, 0x73, 0x4b, 0xf5, 0x5b, 0xf8, 0xb1, 0xba, 0xec, 0xd2, 0x95, 0x48,
	0xfb, 0x45, 0x24, 0x33, 0xb7, 0xda, 0x42, 0xe8, 0xaa, 0xd3, 0x73, 0xcf, 0xf9, 0x9d, 0xdc, 0x61,
	0x48, 0x19, 0xc6, 0x09, 0x08, 0xe9, 0xc5, 0x7c, 0xc0, 0x65, 0x22, 0xdd, 0x61, 0x2a, 0x40, 0xd0,
	0x72, 0xa7, 0x9b, 0xa4, 0x01, 0xb8, 0x7a, 0x88, 0x3f, 0x4e, 0x39, 0x16, 0xb1, 0x50, 0x06, 0x2f,
	0x3b, 0x69, 0xaf, 0xb3, 0x83, 0x84, 0x61, 0x90, 0x06, 0x7d, 0x04, 0x38, 0x0b, 0x6c, 0x14, 0xfa,
	0x1d, 0x1e, 0x44, 0xa8, 0x6e, 0xa3, 0x3a, 0x92, 0x3c, 0x45, 0x89, 0xa1, 0x34, 0x0e, 0x7a, 0x3d,
	0x0e, 0x3e, 0x08, 0x3f, 0x1b, 0xfa, 0xc9, 0x22, 0x42, 0x71, 0x0e, 0x63, 0xce, 0x01, 0xb5, 0xdd,
	0x65, 0xcd, 0xef, 0x25, 0x5d, 0xae, 0x07, 0x07, 0x93, 0x02, 0xd9, 0xbc, 0xd6, 0x8b, 0x3c, 0x42,
	0x00, 0x9c, 0x9e, 0x12, 0x4b, 0x7f, 0x96, 0x6d, 0x56, 0xcd, 0x5a, 0xa9, 0xbe, 0xef, 0xe6, 0x2d,
	0xe6, 0x3e, 0x28, 0x4f, 0xa3, 0x38, 0xf9, 0xac, 0x18, 0x4d, 0x4c, 0xd0, 0x13, 0x62, 0x45, 0xe1,
	0x0d, 0x0f, 0x22, 0xfb, 0xcf, 0xba, 0xec, 0x95, 0xf2, 0x34, 0xd1, 0x4b, 0xcf, 0xc8, 0xff, 0x6c,
	0x81, 0xfb, 0x44, 0x82, 0x5d, 0xa8, 0x16, 0x6a, 0xa5, 0xba, 0x93, 0x9f, 0x7b, 0x92, 0x3c, 0xc5,
	0xc6, 0x9f, 0x04, 0x6d, 0x13, 0xaa, 0x2f, 0xa2, 0x25, 0xb2, 0xf9, 0x6d, 0xa4, 0x38, 0x45, 0xc5,
	0x39, 0xcc, 0xe7, 0x3c, 0xaf, 0xf8, 0x91, 0x98, 0x43, 0xa1, 0xe7, 0x64, 0x43, 0x5d, 0x98, 0x42,
	0xfe, 0x55, 0xc8, 0xbd, 0x7c, 0x64, 0x2b, 0xb3, 0x21, 0xe9, 0x37, 0x43, 0x19, 0x21, 0xea, 0xcf,
	0xa5, 0x18, 0x0d, 0xc0, 0xb6, 0xaa, 0x66, 0xad, 0xd8, 0x5c, 0x52, 0xe8, 0x1d, 0xd9, 0x42, 0x73,
	0x97, 0xab, 0x92, 0x7f, 0xaa, 0xa4, 0xb2, 0xa6, 0x24, 0xb3, 0x62, 0xd1, 0x6a, 0xb6, 0x71, 0x31,
	0x99, 0x31, 0x73, 0x3a, 0x63, 0xe6, 0xd7, 0x8c, 0x99, 0xef, 0x73, 0x66, 0x4c, 0xe7, 0xcc, 0xf8,
	0x98, 0x33, 0xa3, 0x7d, 0x14, 0x27, 0xd0, 0x19, 0x85, 0xee, 0x8b, 0xe8, 0x7b, 0x9a, 0xec, 0xe1,
	0x7b, 0x78, 0x5d, 0x1c, 0xe0, 0x6d, 0xc8, 0x65, 0x68, 0xa9, 0x47, 0x71, 0xfc, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x31, 0x81, 0xc1, 0x77, 0xe3, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TweetLikeList) > 0 {
		for iNdEx := len(m.TweetLikeList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TweetLikeList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.TweetCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TweetCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.TweetList) > 0 {
		for iNdEx := len(m.TweetList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TweetList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.WalletToUserIdList) > 0 {
		for iNdEx := len(m.WalletToUserIdList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WalletToUserIdList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.UserList) > 0 {
		for iNdEx := len(m.UserList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.DbHead != nil {
		{
			size, err := m.DbHead.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.DbHead != nil {
		l = m.DbHead.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.UserList) > 0 {
		for _, e := range m.UserList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WalletToUserIdList) > 0 {
		for _, e := range m.WalletToUserIdList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TweetList) > 0 {
		for _, e := range m.TweetList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.TweetCount != 0 {
		n += 1 + sovGenesis(uint64(m.TweetCount))
	}
	if len(m.TweetLikeList) > 0 {
		for _, e := range m.TweetLikeList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DbHead", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DbHead == nil {
				m.DbHead = &DbHead{}
			}
			if err := m.DbHead.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserList = append(m.UserList, User{})
			if err := m.UserList[len(m.UserList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletToUserIdList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletToUserIdList = append(m.WalletToUserIdList, WalletToUserId{})
			if err := m.WalletToUserIdList[len(m.WalletToUserIdList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TweetList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TweetList = append(m.TweetList, Tweet{})
			if err := m.TweetList[len(m.TweetList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TweetCount", wireType)
			}
			m.TweetCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TweetCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TweetLikeList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TweetLikeList = append(m.TweetLikeList, TweetLike{})
			if err := m.TweetLikeList[len(m.TweetLikeList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
